### ISSUE TITLE
When using `user_properties` feature flag, need to add an explicit dependency against `tiled` crate

### ISSUE THREAD

**Issue by giusdp** [adrien-bon/bevy_ecs_tiled#21]
I'm having a problem with these macros. I was following the user_properties example in my project and got some errors: 

```rust

#[derive(TiledObject, Bundle, Default, Reflect, Debug)]
#[tiled_observer(test_object_observer)]
struct SpawnBundle {
    infos: SpawnInfo,
}

#[derive(TiledClass, Component, Default, Debug, Reflect)] <-- TiledClass use of undeclared crate or module `tiled`
struct SpawnInfo {
    #[tiled_rename = "Type"]
    ty: SpawnType,
}

#[derive(TiledEnum, Default, Reflect, Debug)] <--- TiledEnum use of undeclared crate or module `tiled`
enum SpawnType {
    #[default]
    Unknown,
    Player,
}
```

For the 2 macros it can't find the `tiled` crate dependency. I checked the TiledObject code and it does not use it, so it works. 

The example works normally, but when the code is used in another project those 2 macros have this problem. Or was it my setup wrong?

**Comment by giusdp** [comment]
I think it can be fixed by just adding `pub use tiled;` in the properties prelude.

**Comment by adrien-bon** [comment]
Hi! Thanks for the report :)

I also encountered this issue in my own project.
To work-around this, I had to add  an explicit dependency against `tiled` in my own  `Cargo.toml`.

I though it could be fixed by adding an explicit dependency against `tiled` in the `macros/Cargo.toml` file but: 1/ I did not test this solution so I'm not 100% sure it will work 2/ I did not like it because it would mean to have the same dependency defined in two places.

I don't remember the exact error and maybe adding the `pub use tiled;` could also fix this. However, I think it would be better to directly add it in the `src/lib.rs` file and not condition this to the use of `user_properties` feature flag. After all, we always need this dependency so for me it's logical to have this statement unconditionally (but I'm open to any suggestion :))

I'll give it a try tonight after work.

**Comment by adrien-bon** [comment]
The `pub use tiled;` did the trick and it's now merged in `main` branch.
Many thanks for opening the issue and providing the fix! 👍
